name = "listening-api-20260810"
main = "worker/src/index.js"
compatibility_date = "2024-11-18"

[[d1_databases]]
binding = "DB"
database_name = "listening"
database_id = "e173bcc4-2b41-4e94-8587-89d4db1a8114"
migrations_dir = "migrations"
